# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20231025-231755-wooden-brass

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# null
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 100  
    retrieval_intent: faq
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
  # - name: DucklingEntityExtractor
  #   url: "http://localhost:8000"    # Adjust the URL based on your Duckling server configuration
  #   dimensions: ["time", "number", "amount-of-money", "distance"]
  #   locale: "en_US"
  #   timeout : 3
    #dimensions: ["number"]
  

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies: 
#null
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
    max_history: 7
  - name: RulePolicy
    core_fallback_threshold: 0.4
    enable_fallback_prediction: True
  - name: TEDPolicy
    max_history: 7
    epochs: 100
    constrain_similarities: true
